version: '3.8'

services:
  web:
    build: .
    container_name: flask-aws-connection
    ports:
      - "5000:5000"
    environment:
      - S3_BUCKET=${S3_BUCKET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - RDS_HOST=rds
      - RDS_PORT=5432
      - RDS_DB=${RDS_DB}
      - RDS_USER=${RDS_USER}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - MINIO_URL=http://minio:9000
    depends_on:
      - rds
      - minio

  rds:
    image: postgres:13
    container_name: rds
    environment:
      POSTGRES_DB: ${RDS_DB}
      POSTGRES_USER: ${RDS_USER}
      POSTGRES_PASSWORD: ${RDS_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_KEY}
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  # minio-client:
  #   image: minio/mc
  #   container_name: minio-client
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     sleep 5;
  #     mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY};
  #     mc mb minio/${S3_BUCKET};
  #     mc policy set public minio/${S3_BUCKET};
  #     "

volumes:
  pgdata:
  minio_data:
